version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - .:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7-fpm
    environment:
      - HELLO_NAME=${HELLO_NAME}
    volumes:
      - .:/code
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
